version: '3.3'

volumes:
  foodgram_data:
  static:
  media:

services:

  frontend:
    env_file: ../.env
    image: max158crew/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  db:
    image: postgres:13.0-alpine
    volumes:
      - foodgram_data:/var/lib/postgres/data/
    env_file:
      - ../.env

  backend:
    image: max158crew/foodgram_backend
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  gateway:
    image: max158crew/foodgram_gateway
    volumes:
      - static:/staticfiles/
      - media:/app/media
    ports:
      - 8000:80