# Generated by Django 3.2.3 on 2023-09-13 19:58

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230913_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-name',), 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, validators=[django.core.validators.RegexValidator(code='invalid_color_code', message='Значение должно быть в формате HEX (например, #FF0000)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Цветовой код'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_tag_name', message='Разрешены только буквы, цифры и символ подчеркивания', regex='^[a-zA-Z0-9_а-яА-Я]+$')], verbose_name='Название тэга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=0, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
